// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/font-picks/AlmaraiPlayfair.tsx": () => import("../components/mockups/font-picks/AlmaraiPlayfair.tsx"),
  "./components/mockups/font-picks/IBMPlexFraunces.tsx": () => import("../components/mockups/font-picks/IBMPlexFraunces.tsx"),
  "./components/mockups/font-picks/KufiCormorant.tsx": () => import("../components/mockups/font-picks/KufiCormorant.tsx"),
  "./components/mockups/font-picks/TajawalDMSerif.tsx": () => import("../components/mockups/font-picks/TajawalDMSerif.tsx")
};
